### PR TITLE
Refactor highscore

### PR DESCRIPTION
**Pull request by SimonTer**
Scores will be shown besides the player in the highscores section

### CODE REVIEW

**Comment by SlaughterBrute** [comment]
It looks weird, but maybe this is intentional?
image

**Comment by SlaughterBrute** [comment]
> It looks weird, but maybe this is intentional?
> image

Score values of 1-5 is the same as 6-10

**Comment by Game9954** [comment]
The scores are not on the same indent or all the way to the right.

**Comment by SlaughterBrute** [comment]
OK

**Pull request merged**
